# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# 1. Create Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: atelet
  namespace: ate-system
---
# 2. Define Permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: atelet-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
# 3. Bind Identity to Permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: atelet-binding
subjects:
- kind: ServiceAccount
  name: atelet
  namespace: ate-system
roleRef:
  kind: ClusterRole
  name: atelet-role
  apiGroup: rbac.authorization.k8s.io
---
# 4. Create DaemonSet
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: atelet
  namespace: ate-system
  labels:
    app: atelet
spec:
  selector:
    matchLabels:
      app: atelet
  template:
    metadata:
      labels:
        app: atelet
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      serviceAccountName: atelet
      containers:
      - name: atelet
        image: ko://github.com/agent-substrate/substrate/cmd/atelet
        args:
        - --gcp-auth-for-image-pulls=true
        securityContext:
          privileged: true
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: k8s.namespace.name=$(POD_NAMESPACE),k8s.pod.name=$(POD_NAME),k8s.pod.uid=$(POD_UID),service.instance.id=$(POD_UID)
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://opentelemetry-collector.gke-managed-otel.svc.cluster.local:4317
        - name: ATE_STORAGE_BACKEND
          value: "gcs"
        ports:
        - name: grpc
          containerPort: 8085
          hostPort: 8085
        - name: prometheus
          containerPort: 9090
          hostPort: 9090
          protocol: TCP
        # Connection to ateom gvisor UDS.
        volumeMounts:
        - name: run-ateom
          mountPath: /var/lib/ateom-gvisor
      volumes:
      - name: run-ateom
        hostPath:
          path: /var/lib/ateom-gvisor
          type: DirectoryOrCreate
