# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: atenet-router
  namespace: ate-system
  labels:
    app: atenet-router
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: atenet-router
rules:
- apiGroups:
  - "ate.dev"
  resources:
  - actortemplates
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: atenet-router
subjects:
- kind: ServiceAccount
  name: atenet-router
  namespace: ate-system
roleRef:
  kind: ClusterRole
  name: atenet-router
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atenet-router-envoy-config
  namespace: ate-system
data:
  envoy.yaml: |
    admin:
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901

    node:
      id: substrate-envoy-node
      cluster: substrate-router-cluster

    dynamic_resources:
      lds_config:
        resource_api_version: V3
        ads: {}
      cds_config:
        resource_api_version: V3
        ads: {}
      ads_config:
        api_type: GRPC
        transport_api_version: V3
        grpc_services:
        - envoy_grpc:
            cluster_name: xds_cluster

    static_resources:
      clusters:
      - name: xds_cluster
        connect_timeout: 0.25s
        type: STRICT_DNS
        lb_policy: ROUND_ROBIN
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            explicit_http_config:
              http2_protocol_options: {}
        load_assignment:
          cluster_name: xds_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 18000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: atenet-router
  namespace: ate-system
  labels:
    app: atenet-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atenet-router
  template:
    metadata:
      labels:
        app: atenet-router
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      serviceAccountName: atenet-router
      containers:
      - name: atenet-router
        image: ko://github.com/agent-substrate/substrate/cmd/atenet
        args:
        - "router"
        - "--standalone"
        - "--namespace=ate-system"
        - "--port-http=8080"
        - "--port-xds=18000"
        - "--port-extproc=50051"
        - "--extproc-address=127.0.0.1"
        - "--ateapi-address=api.ate-system.svc:443"
        - "--ateapi-client-cred-bundle=/run/servicedns.podcert.ate.dev/credential-bundle.pem"
        - "--ateapi-server-ca=/run/servicedns.podcert.ate.dev/trust-bundle.pem"
        - "--status-port=4040"
        - "--port-https=8443"
        - "--envoy-cert-path=/run/servicedns.podcert.ate.dev/credential-bundle.pem"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: k8s.namespace.name=$(POD_NAMESPACE),k8s.pod.name=$(POD_NAME),k8s.pod.uid=$(POD_UID),service.instance.id=$(POD_UID)
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://opentelemetry-collector.gke-managed-otel.svc.cluster.local:4317
        ports:
        - name: xds
          containerPort: 18000
        - name: extproc
          containerPort: 50051
        - name: status
          containerPort: 4040
        - name: metrics
          containerPort: 9090
        volumeMounts:
        - name: "servicedns"
          mountPath: "/run/servicedns.podcert.ate.dev"
          readOnly: true
      - name: envoy
        image: envoyproxy/envoy:v1.30-latest
        command:
        - "/usr/local/bin/envoy"
        - "-c"
        - "/etc/envoy/envoy.yaml"
        - "--component-log-level"
        - "upstream:debug,router:debug,ext_proc:debug"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        - name: admin
          containerPort: 9901
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy
        - name: "servicedns"
          mountPath: "/run/servicedns.podcert.ate.dev"
      volumes:
      - name: envoy-config
        configMap:
          name: atenet-router-envoy-config
      - name: "servicedns"
        projected:
          sources:
          - podCertificate:
              signerName: servicedns.podcert.ate.dev/identity
              keyType: ECDSAP256
              credentialBundlePath: credential-bundle.pem
          - clusterTrustBundle:
              signerName: servicedns.podcert.ate.dev/identity
              labelSelector:
                matchLabels:
                  podcert.ate.dev/canarying: live
              path: trust-bundle.pem
---
apiVersion: v1
kind: Service
metadata:
  name: atenet-router
  namespace: ate-system
spec:
  type: ClusterIP
  selector:
    app: atenet-router
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
