// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: ateapi.proto

package ateapipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Control_GetActor_FullMethodName                   = "/ateapi.Control/GetActor"
	Control_CreateActor_FullMethodName                = "/ateapi.Control/CreateActor"
	Control_UpdateActor_FullMethodName                = "/ateapi.Control/UpdateActor"
	Control_SuspendActor_FullMethodName               = "/ateapi.Control/SuspendActor"
	Control_PauseActor_FullMethodName                 = "/ateapi.Control/PauseActor"
	Control_ResumeActor_FullMethodName                = "/ateapi.Control/ResumeActor"
	Control_DeleteActor_FullMethodName                = "/ateapi.Control/DeleteActor"
	Control_GetActorSnapshot_FullMethodName           = "/ateapi.Control/GetActorSnapshot"
	Control_ListActorSnapshots_FullMethodName         = "/ateapi.Control/ListActorSnapshots"
	Control_TagActorSnapshot_FullMethodName           = "/ateapi.Control/TagActorSnapshot"
	Control_UpdateActorSnapshotTag_FullMethodName     = "/ateapi.Control/UpdateActorSnapshotTag"
	Control_DeleteActorSnapshotTag_FullMethodName     = "/ateapi.Control/DeleteActorSnapshotTag"
	Control_ListWorkers_FullMethodName                = "/ateapi.Control/ListWorkers"
	Control_ListActors_FullMethodName                 = "/ateapi.Control/ListActors"
	Control_CreateAtespace_FullMethodName             = "/ateapi.Control/CreateAtespace"
	Control_GetAtespace_FullMethodName                = "/ateapi.Control/GetAtespace"
	Control_ListAtespaces_FullMethodName              = "/ateapi.Control/ListAtespaces"
	Control_DeleteAtespace_FullMethodName             = "/ateapi.Control/DeleteAtespace"
	Control_CreateActorTemplate_FullMethodName        = "/ateapi.Control/CreateActorTemplate"
	Control_GetActorTemplate_FullMethodName           = "/ateapi.Control/GetActorTemplate"
	Control_UpdateActorTemplate_FullMethodName        = "/ateapi.Control/UpdateActorTemplate"
	Control_ListActorTemplates_FullMethodName         = "/ateapi.Control/ListActorTemplates"
	Control_DeleteActorTemplate_FullMethodName        = "/ateapi.Control/DeleteActorTemplate"
	Control_CreateActorTemplateVersion_FullMethodName = "/ateapi.Control/CreateActorTemplateVersion"
	Control_GetActorTemplateVersion_FullMethodName    = "/ateapi.Control/GetActorTemplateVersion"
	Control_ListActorTemplateVersions_FullMethodName  = "/ateapi.Control/ListActorTemplateVersions"
	Control_DeleteActorTemplateVersion_FullMethodName = "/ateapi.Control/DeleteActorTemplateVersion"
)

// ControlClient is the client API for Control service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Control is the primary RPC interface for Agentic Substrate.
type ControlClient interface {
	// Get an Actor.
	GetActor(ctx context.Context, in *GetActorRequest, opts ...grpc.CallOption) (*Actor, error)
	// Create a new Actor deriving from a given ActorTemplate.
	CreateActor(ctx context.Context, in *CreateActorRequest, opts ...grpc.CallOption) (*Actor, error)
	// Update mutable fields on an existing Actor.
	UpdateActor(ctx context.Context, in *UpdateActorRequest, opts ...grpc.CallOption) (*Actor, error)
	// Suspend a given actor to a new snapshot.
	SuspendActor(ctx context.Context, in *SuspendActorRequest, opts ...grpc.CallOption) (*SuspendActorResponse, error)
	// Pause a given actor and keep its snapshots on node VM.
	PauseActor(ctx context.Context, in *PauseActorRequest, opts ...grpc.CallOption) (*PauseActorResponse, error)
	// Resume an actor from its latest snapshot.
	ResumeActor(ctx context.Context, in *ResumeActorRequest, opts ...grpc.CallOption) (*ResumeActorResponse, error)
	// Delete an actor. Only suspended actors can be deleted.
	DeleteActor(ctx context.Context, in *DeleteActorRequest, opts ...grpc.CallOption) (*Actor, error)
	// Get an ActorSnapshot.
	GetActorSnapshot(ctx context.Context, in *GetActorSnapshotRequest, opts ...grpc.CallOption) (*ActorSnapshot, error)
	// List ActorSnapshots.
	ListActorSnapshots(ctx context.Context, in *ListActorSnapshotsRequest, opts ...grpc.CallOption) (*ListActorSnapshotsResponse, error)
	// Add an Atespace-owned, stable name for an ActorSnapshot.
	TagActorSnapshot(ctx context.Context, in *TagActorSnapshotRequest, opts ...grpc.CallOption) (*ActorSnapshotTag, error)
	// Publish or unpublish an ActorSnapshot tag without changing its address.
	UpdateActorSnapshotTag(ctx context.Context, in *UpdateActorSnapshotTagRequest, opts ...grpc.CallOption) (*ActorSnapshotTag, error)
	// Delete an ActorSnapshot tag. The snapshot becomes garbage-collectable when
	// its final tag is deleted.
	DeleteActorSnapshotTag(ctx context.Context, in *DeleteActorSnapshotTagRequest, opts ...grpc.CallOption) (*ActorSnapshotTag, error)
	// List Workers.
	ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error)
	// List Actors.
	ListActors(ctx context.Context, in *ListActorsRequest, opts ...grpc.CallOption) (*ListActorsResponse, error)
	// Create a new Atespace. Substrate-native, stored in Redis.
	CreateAtespace(ctx context.Context, in *CreateAtespaceRequest, opts ...grpc.CallOption) (*Atespace, error)
	// Get an Atespace by name.
	GetAtespace(ctx context.Context, in *GetAtespaceRequest, opts ...grpc.CallOption) (*Atespace, error)
	// List Atespaces.
	ListAtespaces(ctx context.Context, in *ListAtespacesRequest, opts ...grpc.CallOption) (*ListAtespacesResponse, error)
	// Delete an empty Atespace. Rejects (FailedPrecondition) if any Actors or
	// ActorSnapshotTags remain.
	DeleteAtespace(ctx context.Context, in *DeleteAtespaceRequest, opts ...grpc.CallOption) (*Atespace, error)
	CreateActorTemplate(ctx context.Context, in *CreateActorTemplateRequest, opts ...grpc.CallOption) (*ActorTemplate, error)
	// Get an ActorTemplate by name.
	GetActorTemplate(ctx context.Context, in *GetActorTemplateRequest, opts ...grpc.CallOption) (*ActorTemplate, error)
	// Update mutable fields on an existing ActorTemplate.
	UpdateActorTemplate(ctx context.Context, in *UpdateActorTemplateRequest, opts ...grpc.CallOption) (*ActorTemplate, error)
	ListActorTemplates(ctx context.Context, in *ListActorTemplatesRequest, opts ...grpc.CallOption) (*ListActorTemplatesResponse, error)
	// Delete an ActorTemplate. Rejects (FailedPrecondition) while any of its
	// ActorTemplateVersions exist.
	DeleteActorTemplate(ctx context.Context, in *DeleteActorTemplateRequest, opts ...grpc.CallOption) (*ActorTemplate, error)
	// Create a new ActorTemplateVersion under an existing ActorTemplate
	// (FailedPrecondition if the parent does not exist).
	CreateActorTemplateVersion(ctx context.Context, in *CreateActorTemplateVersionRequest, opts ...grpc.CallOption) (*ActorTemplateVersion, error)
	// Get an ActorTemplateVersion by name.
	GetActorTemplateVersion(ctx context.Context, in *GetActorTemplateVersionRequest, opts ...grpc.CallOption) (*ActorTemplateVersion, error)
	// List ActorTemplateVersions, optionally filtered to one ActorTemplate.
	ListActorTemplateVersions(ctx context.Context, in *ListActorTemplateVersionsRequest, opts ...grpc.CallOption) (*ListActorTemplateVersionsResponse, error)
	// Delete an ActorTemplateVersion together with its golden actor and golden
	// snapshot in the reserved ate-golden atespace. Rejects (FailedPrecondition)
	// while the version is its parent's default_version_on_create or while any
	// Actor pins it.
	DeleteActorTemplateVersion(ctx context.Context, in *DeleteActorTemplateVersionRequest, opts ...grpc.CallOption) (*ActorTemplateVersion, error)
}

type controlClient struct {
	cc grpc.ClientConnInterface
}

func NewControlClient(cc grpc.ClientConnInterface) ControlClient {
	return &controlClient{cc}
}

func (c *controlClient) GetActor(ctx context.Context, in *GetActorRequest, opts ...grpc.CallOption) (*Actor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Actor)
	err := c.cc.Invoke(ctx, Control_GetActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) CreateActor(ctx context.Context, in *CreateActorRequest, opts ...grpc.CallOption) (*Actor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Actor)
	err := c.cc.Invoke(ctx, Control_CreateActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) UpdateActor(ctx context.Context, in *UpdateActorRequest, opts ...grpc.CallOption) (*Actor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Actor)
	err := c.cc.Invoke(ctx, Control_UpdateActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) SuspendActor(ctx context.Context, in *SuspendActorRequest, opts ...grpc.CallOption) (*SuspendActorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendActorResponse)
	err := c.cc.Invoke(ctx, Control_SuspendActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) PauseActor(ctx context.Context, in *PauseActorRequest, opts ...grpc.CallOption) (*PauseActorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseActorResponse)
	err := c.cc.Invoke(ctx, Control_PauseActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) ResumeActor(ctx context.Context, in *ResumeActorRequest, opts ...grpc.CallOption) (*ResumeActorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeActorResponse)
	err := c.cc.Invoke(ctx, Control_ResumeActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) DeleteActor(ctx context.Context, in *DeleteActorRequest, opts ...grpc.CallOption) (*Actor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Actor)
	err := c.cc.Invoke(ctx, Control_DeleteActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) GetActorSnapshot(ctx context.Context, in *GetActorSnapshotRequest, opts ...grpc.CallOption) (*ActorSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActorSnapshot)
	err := c.cc.Invoke(ctx, Control_GetActorSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) ListActorSnapshots(ctx context.Context, in *ListActorSnapshotsRequest, opts ...grpc.CallOption) (*ListActorSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActorSnapshotsResponse)
	err := c.cc.Invoke(ctx, Control_ListActorSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) TagActorSnapshot(ctx context.Context, in *TagActorSnapshotRequest, opts ...grpc.CallOption) (*ActorSnapshotTag, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActorSnapshotTag)
	err := c.cc.Invoke(ctx, Control_TagActorSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) UpdateActorSnapshotTag(ctx context.Context, in *UpdateActorSnapshotTagRequest, opts ...grpc.CallOption) (*ActorSnapshotTag, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActorSnapshotTag)
	err := c.cc.Invoke(ctx, Control_UpdateActorSnapshotTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) DeleteActorSnapshotTag(ctx context.Context, in *DeleteActorSnapshotTagRequest, opts ...grpc.CallOption) (*ActorSnapshotTag, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActorSnapshotTag)
	err := c.cc.Invoke(ctx, Control_DeleteActorSnapshotTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkersResponse)
	err := c.cc.Invoke(ctx, Control_ListWorkers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) ListActors(ctx context.Context, in *ListActorsRequest, opts ...grpc.CallOption) (*ListActorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActorsResponse)
	err := c.cc.Invoke(ctx, Control_ListActors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) CreateAtespace(ctx context.Context, in *CreateAtespaceRequest, opts ...grpc.CallOption) (*Atespace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Atespace)
	err := c.cc.Invoke(ctx, Control_CreateAtespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) GetAtespace(ctx context.Context, in *GetAtespaceRequest, opts ...grpc.CallOption) (*Atespace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Atespace)
	err := c.cc.Invoke(ctx, Control_GetAtespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) ListAtespaces(ctx context.Context, in *ListAtespacesRequest, opts ...grpc.CallOption) (*ListAtespacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAtespacesResponse)
	err := c.cc.Invoke(ctx, Control_ListAtespaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) DeleteAtespace(ctx context.Context, in *DeleteAtespaceRequest, opts ...grpc.CallOption) (*Atespace, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Atespace)
	err := c.cc.Invoke(ctx, Control_DeleteAtespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) CreateActorTemplate(ctx context.Context, in *CreateActorTemplateRequest, opts ...grpc.CallOption) (*ActorTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActorTemplate)
	err := c.cc.Invoke(ctx, Control_CreateActorTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) GetActorTemplate(ctx context.Context, in *GetActorTemplateRequest, opts ...grpc.CallOption) (*ActorTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActorTemplate)
	err := c.cc.Invoke(ctx, Control_GetActorTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) UpdateActorTemplate(ctx context.Context, in *UpdateActorTemplateRequest, opts ...grpc.CallOption) (*ActorTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActorTemplate)
	err := c.cc.Invoke(ctx, Control_UpdateActorTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) ListActorTemplates(ctx context.Context, in *ListActorTemplatesRequest, opts ...grpc.CallOption) (*ListActorTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActorTemplatesResponse)
	err := c.cc.Invoke(ctx, Control_ListActorTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) DeleteActorTemplate(ctx context.Context, in *DeleteActorTemplateRequest, opts ...grpc.CallOption) (*ActorTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActorTemplate)
	err := c.cc.Invoke(ctx, Control_DeleteActorTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) CreateActorTemplateVersion(ctx context.Context, in *CreateActorTemplateVersionRequest, opts ...grpc.CallOption) (*ActorTemplateVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActorTemplateVersion)
	err := c.cc.Invoke(ctx, Control_CreateActorTemplateVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) GetActorTemplateVersion(ctx context.Context, in *GetActorTemplateVersionRequest, opts ...grpc.CallOption) (*ActorTemplateVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActorTemplateVersion)
	err := c.cc.Invoke(ctx, Control_GetActorTemplateVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) ListActorTemplateVersions(ctx context.Context, in *ListActorTemplateVersionsRequest, opts ...grpc.CallOption) (*ListActorTemplateVersionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActorTemplateVersionsResponse)
	err := c.cc.Invoke(ctx, Control_ListActorTemplateVersions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlClient) DeleteActorTemplateVersion(ctx context.Context, in *DeleteActorTemplateVersionRequest, opts ...grpc.CallOption) (*ActorTemplateVersion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActorTemplateVersion)
	err := c.cc.Invoke(ctx, Control_DeleteActorTemplateVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServer is the server API for Control service.
// All implementations must embed UnimplementedControlServer
// for forward compatibility.
//
// Control is the primary RPC interface for Agentic Substrate.
type ControlServer interface {
	// Get an Actor.
	GetActor(context.Context, *GetActorRequest) (*Actor, error)
	// Create a new Actor deriving from a given ActorTemplate.
	CreateActor(context.Context, *CreateActorRequest) (*Actor, error)
	// Update mutable fields on an existing Actor.
	UpdateActor(context.Context, *UpdateActorRequest) (*Actor, error)
	// Suspend a given actor to a new snapshot.
	SuspendActor(context.Context, *SuspendActorRequest) (*SuspendActorResponse, error)
	// Pause a given actor and keep its snapshots on node VM.
	PauseActor(context.Context, *PauseActorRequest) (*PauseActorResponse, error)
	// Resume an actor from its latest snapshot.
	ResumeActor(context.Context, *ResumeActorRequest) (*ResumeActorResponse, error)
	// Delete an actor. Only suspended actors can be deleted.
	DeleteActor(context.Context, *DeleteActorRequest) (*Actor, error)
	// Get an ActorSnapshot.
	GetActorSnapshot(context.Context, *GetActorSnapshotRequest) (*ActorSnapshot, error)
	// List ActorSnapshots.
	ListActorSnapshots(context.Context, *ListActorSnapshotsRequest) (*ListActorSnapshotsResponse, error)
	// Add an Atespace-owned, stable name for an ActorSnapshot.
	TagActorSnapshot(context.Context, *TagActorSnapshotRequest) (*ActorSnapshotTag, error)
	// Publish or unpublish an ActorSnapshot tag without changing its address.
	UpdateActorSnapshotTag(context.Context, *UpdateActorSnapshotTagRequest) (*ActorSnapshotTag, error)
	// Delete an ActorSnapshot tag. The snapshot becomes garbage-collectable when
	// its final tag is deleted.
	DeleteActorSnapshotTag(context.Context, *DeleteActorSnapshotTagRequest) (*ActorSnapshotTag, error)
	// List Workers.
	ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error)
	// List Actors.
	ListActors(context.Context, *ListActorsRequest) (*ListActorsResponse, error)
	// Create a new Atespace. Substrate-native, stored in Redis.
	CreateAtespace(context.Context, *CreateAtespaceRequest) (*Atespace, error)
	// Get an Atespace by name.
	GetAtespace(context.Context, *GetAtespaceRequest) (*Atespace, error)
	// List Atespaces.
	ListAtespaces(context.Context, *ListAtespacesRequest) (*ListAtespacesResponse, error)
	// Delete an empty Atespace. Rejects (FailedPrecondition) if any Actors or
	// ActorSnapshotTags remain.
	DeleteAtespace(context.Context, *DeleteAtespaceRequest) (*Atespace, error)
	CreateActorTemplate(context.Context, *CreateActorTemplateRequest) (*ActorTemplate, error)
	// Get an ActorTemplate by name.
	GetActorTemplate(context.Context, *GetActorTemplateRequest) (*ActorTemplate, error)
	// Update mutable fields on an existing ActorTemplate.
	UpdateActorTemplate(context.Context, *UpdateActorTemplateRequest) (*ActorTemplate, error)
	ListActorTemplates(context.Context, *ListActorTemplatesRequest) (*ListActorTemplatesResponse, error)
	// Delete an ActorTemplate. Rejects (FailedPrecondition) while any of its
	// ActorTemplateVersions exist.
	DeleteActorTemplate(context.Context, *DeleteActorTemplateRequest) (*ActorTemplate, error)
	// Create a new ActorTemplateVersion under an existing ActorTemplate
	// (FailedPrecondition if the parent does not exist).
	CreateActorTemplateVersion(context.Context, *CreateActorTemplateVersionRequest) (*ActorTemplateVersion, error)
	// Get an ActorTemplateVersion by name.
	GetActorTemplateVersion(context.Context, *GetActorTemplateVersionRequest) (*ActorTemplateVersion, error)
	// List ActorTemplateVersions, optionally filtered to one ActorTemplate.
	ListActorTemplateVersions(context.Context, *ListActorTemplateVersionsRequest) (*ListActorTemplateVersionsResponse, error)
	// Delete an ActorTemplateVersion together with its golden actor and golden
	// snapshot in the reserved ate-golden atespace. Rejects (FailedPrecondition)
	// while the version is its parent's default_version_on_create or while any
	// Actor pins it.
	DeleteActorTemplateVersion(context.Context, *DeleteActorTemplateVersionRequest) (*ActorTemplateVersion, error)
	mustEmbedUnimplementedControlServer()
}

// UnimplementedControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServer struct{}

func (UnimplementedControlServer) GetActor(context.Context, *GetActorRequest) (*Actor, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActor not implemented")
}
func (UnimplementedControlServer) CreateActor(context.Context, *CreateActorRequest) (*Actor, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateActor not implemented")
}
func (UnimplementedControlServer) UpdateActor(context.Context, *UpdateActorRequest) (*Actor, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateActor not implemented")
}
func (UnimplementedControlServer) SuspendActor(context.Context, *SuspendActorRequest) (*SuspendActorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendActor not implemented")
}
func (UnimplementedControlServer) PauseActor(context.Context, *PauseActorRequest) (*PauseActorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseActor not implemented")
}
func (UnimplementedControlServer) ResumeActor(context.Context, *ResumeActorRequest) (*ResumeActorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeActor not implemented")
}
func (UnimplementedControlServer) DeleteActor(context.Context, *DeleteActorRequest) (*Actor, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteActor not implemented")
}
func (UnimplementedControlServer) GetActorSnapshot(context.Context, *GetActorSnapshotRequest) (*ActorSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActorSnapshot not implemented")
}
func (UnimplementedControlServer) ListActorSnapshots(context.Context, *ListActorSnapshotsRequest) (*ListActorSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActorSnapshots not implemented")
}
func (UnimplementedControlServer) TagActorSnapshot(context.Context, *TagActorSnapshotRequest) (*ActorSnapshotTag, error) {
	return nil, status.Error(codes.Unimplemented, "method TagActorSnapshot not implemented")
}
func (UnimplementedControlServer) UpdateActorSnapshotTag(context.Context, *UpdateActorSnapshotTagRequest) (*ActorSnapshotTag, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateActorSnapshotTag not implemented")
}
func (UnimplementedControlServer) DeleteActorSnapshotTag(context.Context, *DeleteActorSnapshotTagRequest) (*ActorSnapshotTag, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteActorSnapshotTag not implemented")
}
func (UnimplementedControlServer) ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkers not implemented")
}
func (UnimplementedControlServer) ListActors(context.Context, *ListActorsRequest) (*ListActorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActors not implemented")
}
func (UnimplementedControlServer) CreateAtespace(context.Context, *CreateAtespaceRequest) (*Atespace, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAtespace not implemented")
}
func (UnimplementedControlServer) GetAtespace(context.Context, *GetAtespaceRequest) (*Atespace, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAtespace not implemented")
}
func (UnimplementedControlServer) ListAtespaces(context.Context, *ListAtespacesRequest) (*ListAtespacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAtespaces not implemented")
}
func (UnimplementedControlServer) DeleteAtespace(context.Context, *DeleteAtespaceRequest) (*Atespace, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAtespace not implemented")
}
func (UnimplementedControlServer) CreateActorTemplate(context.Context, *CreateActorTemplateRequest) (*ActorTemplate, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateActorTemplate not implemented")
}
func (UnimplementedControlServer) GetActorTemplate(context.Context, *GetActorTemplateRequest) (*ActorTemplate, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActorTemplate not implemented")
}
func (UnimplementedControlServer) UpdateActorTemplate(context.Context, *UpdateActorTemplateRequest) (*ActorTemplate, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateActorTemplate not implemented")
}
func (UnimplementedControlServer) ListActorTemplates(context.Context, *ListActorTemplatesRequest) (*ListActorTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActorTemplates not implemented")
}
func (UnimplementedControlServer) DeleteActorTemplate(context.Context, *DeleteActorTemplateRequest) (*ActorTemplate, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteActorTemplate not implemented")
}
func (UnimplementedControlServer) CreateActorTemplateVersion(context.Context, *CreateActorTemplateVersionRequest) (*ActorTemplateVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateActorTemplateVersion not implemented")
}
func (UnimplementedControlServer) GetActorTemplateVersion(context.Context, *GetActorTemplateVersionRequest) (*ActorTemplateVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActorTemplateVersion not implemented")
}
func (UnimplementedControlServer) ListActorTemplateVersions(context.Context, *ListActorTemplateVersionsRequest) (*ListActorTemplateVersionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActorTemplateVersions not implemented")
}
func (UnimplementedControlServer) DeleteActorTemplateVersion(context.Context, *DeleteActorTemplateVersionRequest) (*ActorTemplateVersion, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteActorTemplateVersion not implemented")
}
func (UnimplementedControlServer) mustEmbedUnimplementedControlServer() {}
func (UnimplementedControlServer) testEmbeddedByValue()                 {}

// UnsafeControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServer will
// result in compilation errors.
type UnsafeControlServer interface {
	mustEmbedUnimplementedControlServer()
}

func RegisterControlServer(s grpc.ServiceRegistrar, srv ControlServer) {
	// If the following call panics, it indicates UnimplementedControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Control_ServiceDesc, srv)
}

func _Control_GetActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).GetActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_GetActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).GetActor(ctx, req.(*GetActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_CreateActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).CreateActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_CreateActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).CreateActor(ctx, req.(*CreateActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_UpdateActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).UpdateActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_UpdateActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).UpdateActor(ctx, req.(*UpdateActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_SuspendActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).SuspendActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_SuspendActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).SuspendActor(ctx, req.(*SuspendActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_PauseActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).PauseActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_PauseActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).PauseActor(ctx, req.(*PauseActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_ResumeActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).ResumeActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_ResumeActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).ResumeActor(ctx, req.(*ResumeActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_DeleteActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).DeleteActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_DeleteActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).DeleteActor(ctx, req.(*DeleteActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_GetActorSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActorSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).GetActorSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_GetActorSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).GetActorSnapshot(ctx, req.(*GetActorSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_ListActorSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActorSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).ListActorSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_ListActorSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).ListActorSnapshots(ctx, req.(*ListActorSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_TagActorSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TagActorSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).TagActorSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_TagActorSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).TagActorSnapshot(ctx, req.(*TagActorSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_UpdateActorSnapshotTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateActorSnapshotTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).UpdateActorSnapshotTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_UpdateActorSnapshotTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).UpdateActorSnapshotTag(ctx, req.(*UpdateActorSnapshotTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_DeleteActorSnapshotTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteActorSnapshotTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).DeleteActorSnapshotTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_DeleteActorSnapshotTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).DeleteActorSnapshotTag(ctx, req.(*DeleteActorSnapshotTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_ListWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).ListWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_ListWorkers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).ListWorkers(ctx, req.(*ListWorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_ListActors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).ListActors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_ListActors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).ListActors(ctx, req.(*ListActorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_CreateAtespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAtespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).CreateAtespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_CreateAtespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).CreateAtespace(ctx, req.(*CreateAtespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_GetAtespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAtespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).GetAtespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_GetAtespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).GetAtespace(ctx, req.(*GetAtespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_ListAtespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAtespacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).ListAtespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_ListAtespaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).ListAtespaces(ctx, req.(*ListAtespacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_DeleteAtespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAtespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).DeleteAtespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_DeleteAtespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).DeleteAtespace(ctx, req.(*DeleteAtespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_CreateActorTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateActorTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).CreateActorTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_CreateActorTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).CreateActorTemplate(ctx, req.(*CreateActorTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_GetActorTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActorTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).GetActorTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_GetActorTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).GetActorTemplate(ctx, req.(*GetActorTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_UpdateActorTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateActorTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).UpdateActorTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_UpdateActorTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).UpdateActorTemplate(ctx, req.(*UpdateActorTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_ListActorTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActorTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).ListActorTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_ListActorTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).ListActorTemplates(ctx, req.(*ListActorTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_DeleteActorTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteActorTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).DeleteActorTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_DeleteActorTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).DeleteActorTemplate(ctx, req.(*DeleteActorTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_CreateActorTemplateVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateActorTemplateVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).CreateActorTemplateVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_CreateActorTemplateVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).CreateActorTemplateVersion(ctx, req.(*CreateActorTemplateVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_GetActorTemplateVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActorTemplateVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).GetActorTemplateVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_GetActorTemplateVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).GetActorTemplateVersion(ctx, req.(*GetActorTemplateVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_ListActorTemplateVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActorTemplateVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).ListActorTemplateVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_ListActorTemplateVersions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).ListActorTemplateVersions(ctx, req.(*ListActorTemplateVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Control_DeleteActorTemplateVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteActorTemplateVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).DeleteActorTemplateVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Control_DeleteActorTemplateVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).DeleteActorTemplateVersion(ctx, req.(*DeleteActorTemplateVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Control_ServiceDesc is the grpc.ServiceDesc for Control service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Control_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ateapi.Control",
	HandlerType: (*ControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActor",
			Handler:    _Control_GetActor_Handler,
		},
		{
			MethodName: "CreateActor",
			Handler:    _Control_CreateActor_Handler,
		},
		{
			MethodName: "UpdateActor",
			Handler:    _Control_UpdateActor_Handler,
		},
		{
			MethodName: "SuspendActor",
			Handler:    _Control_SuspendActor_Handler,
		},
		{
			MethodName: "PauseActor",
			Handler:    _Control_PauseActor_Handler,
		},
		{
			MethodName: "ResumeActor",
			Handler:    _Control_ResumeActor_Handler,
		},
		{
			MethodName: "DeleteActor",
			Handler:    _Control_DeleteActor_Handler,
		},
		{
			MethodName: "GetActorSnapshot",
			Handler:    _Control_GetActorSnapshot_Handler,
		},
		{
			MethodName: "ListActorSnapshots",
			Handler:    _Control_ListActorSnapshots_Handler,
		},
		{
			MethodName: "TagActorSnapshot",
			Handler:    _Control_TagActorSnapshot_Handler,
		},
		{
			MethodName: "UpdateActorSnapshotTag",
			Handler:    _Control_UpdateActorSnapshotTag_Handler,
		},
		{
			MethodName: "DeleteActorSnapshotTag",
			Handler:    _Control_DeleteActorSnapshotTag_Handler,
		},
		{
			MethodName: "ListWorkers",
			Handler:    _Control_ListWorkers_Handler,
		},
		{
			MethodName: "ListActors",
			Handler:    _Control_ListActors_Handler,
		},
		{
			MethodName: "CreateAtespace",
			Handler:    _Control_CreateAtespace_Handler,
		},
		{
			MethodName: "GetAtespace",
			Handler:    _Control_GetAtespace_Handler,
		},
		{
			MethodName: "ListAtespaces",
			Handler:    _Control_ListAtespaces_Handler,
		},
		{
			MethodName: "DeleteAtespace",
			Handler:    _Control_DeleteAtespace_Handler,
		},
		{
			MethodName: "CreateActorTemplate",
			Handler:    _Control_CreateActorTemplate_Handler,
		},
		{
			MethodName: "GetActorTemplate",
			Handler:    _Control_GetActorTemplate_Handler,
		},
		{
			MethodName: "UpdateActorTemplate",
			Handler:    _Control_UpdateActorTemplate_Handler,
		},
		{
			MethodName: "ListActorTemplates",
			Handler:    _Control_ListActorTemplates_Handler,
		},
		{
			MethodName: "DeleteActorTemplate",
			Handler:    _Control_DeleteActorTemplate_Handler,
		},
		{
			MethodName: "CreateActorTemplateVersion",
			Handler:    _Control_CreateActorTemplateVersion_Handler,
		},
		{
			MethodName: "GetActorTemplateVersion",
			Handler:    _Control_GetActorTemplateVersion_Handler,
		},
		{
			MethodName: "ListActorTemplateVersions",
			Handler:    _Control_ListActorTemplateVersions_Handler,
		},
		{
			MethodName: "DeleteActorTemplateVersion",
			Handler:    _Control_DeleteActorTemplateVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ateapi.proto",
}

const (
	Debug_DebugClear_FullMethodName = "/ateapi.Debug/DebugClear"
)

// DebugClient is the client API for Debug service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Debug is the RPC interface for administrative and debugging operations
// (such as wiping state during development).
type DebugClient interface {
	// Debugging: drop all data from the ate database.
	DebugClear(ctx context.Context, in *DebugClearRequest, opts ...grpc.CallOption) (*DebugClearResponse, error)
}

type debugClient struct {
	cc grpc.ClientConnInterface
}

func NewDebugClient(cc grpc.ClientConnInterface) DebugClient {
	return &debugClient{cc}
}

func (c *debugClient) DebugClear(ctx context.Context, in *DebugClearRequest, opts ...grpc.CallOption) (*DebugClearResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DebugClearResponse)
	err := c.cc.Invoke(ctx, Debug_DebugClear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DebugServer is the server API for Debug service.
// All implementations must embed UnimplementedDebugServer
// for forward compatibility.
//
// Debug is the RPC interface for administrative and debugging operations
// (such as wiping state during development).
type DebugServer interface {
	// Debugging: drop all data from the ate database.
	DebugClear(context.Context, *DebugClearRequest) (*DebugClearResponse, error)
	mustEmbedUnimplementedDebugServer()
}

// UnimplementedDebugServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDebugServer struct{}

func (UnimplementedDebugServer) DebugClear(context.Context, *DebugClearRequest) (*DebugClearResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DebugClear not implemented")
}
func (UnimplementedDebugServer) mustEmbedUnimplementedDebugServer() {}
func (UnimplementedDebugServer) testEmbeddedByValue()               {}

// UnsafeDebugServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DebugServer will
// result in compilation errors.
type UnsafeDebugServer interface {
	mustEmbedUnimplementedDebugServer()
}

func RegisterDebugServer(s grpc.ServiceRegistrar, srv DebugServer) {
	// If the following call panics, it indicates UnimplementedDebugServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Debug_ServiceDesc, srv)
}

func _Debug_DebugClear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DebugClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServer).DebugClear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Debug_DebugClear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServer).DebugClear(ctx, req.(*DebugClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Debug_ServiceDesc is the grpc.ServiceDesc for Debug service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Debug_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ateapi.Debug",
	HandlerType: (*DebugServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DebugClear",
			Handler:    _Debug_DebugClear_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ateapi.proto",
}

const (
	ActorIdentity_MintJWT_FullMethodName  = "/ateapi.ActorIdentity/MintJWT"
	ActorIdentity_MintCert_FullMethodName = "/ateapi.ActorIdentity/MintCert"
)

// ActorIdentityClient is the client API for ActorIdentity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ActorIdentity allows substrate workloads to exchange their
// infrastructure-level credentials (k8s service account token, etc.) for a
// substrate actor-level credential. A given substrate actor might migrate
// between many different physical workers over the course of its lifecycle,
// whereas the actor credential's identity will be stable for the life of the
// actor.
type ActorIdentityClient interface {
	// Request an Actor Identity JWT.
	//
	// To call this RPC, you must be authenticated as the Kubernetes Pod that is
	// currently running the requested actor.
	MintJWT(ctx context.Context, in *MintJWTRequest, opts ...grpc.CallOption) (*MintJWTResponse, error)
	// Request an Actor Identity Certificate for an actor.
	//
	// Actors do not call this RPC themselves. The atelet hosting the actor calls
	// it on the actor's behalf, authenticating with its own client certificate
	// rather than a bearer token.
	//
	// Authorization is decided on that client certificate and the worker
	// identity attested by atelet. Ateapi verifies that the worker is assigned to
	// the actor and that the actor points back to that exact worker before signing.
	//
	// The certificate in the response is the actor's identity, not the atelet's.
	MintCert(ctx context.Context, in *MintCertRequest, opts ...grpc.CallOption) (*MintCertResponse, error)
}

type actorIdentityClient struct {
	cc grpc.ClientConnInterface
}

func NewActorIdentityClient(cc grpc.ClientConnInterface) ActorIdentityClient {
	return &actorIdentityClient{cc}
}

func (c *actorIdentityClient) MintJWT(ctx context.Context, in *MintJWTRequest, opts ...grpc.CallOption) (*MintJWTResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintJWTResponse)
	err := c.cc.Invoke(ctx, ActorIdentity_MintJWT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actorIdentityClient) MintCert(ctx context.Context, in *MintCertRequest, opts ...grpc.CallOption) (*MintCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintCertResponse)
	err := c.cc.Invoke(ctx, ActorIdentity_MintCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActorIdentityServer is the server API for ActorIdentity service.
// All implementations must embed UnimplementedActorIdentityServer
// for forward compatibility.
//
// ActorIdentity allows substrate workloads to exchange their
// infrastructure-level credentials (k8s service account token, etc.) for a
// substrate actor-level credential. A given substrate actor might migrate
// between many different physical workers over the course of its lifecycle,
// whereas the actor credential's identity will be stable for the life of the
// actor.
type ActorIdentityServer interface {
	// Request an Actor Identity JWT.
	//
	// To call this RPC, you must be authenticated as the Kubernetes Pod that is
	// currently running the requested actor.
	MintJWT(context.Context, *MintJWTRequest) (*MintJWTResponse, error)
	// Request an Actor Identity Certificate for an actor.
	//
	// Actors do not call this RPC themselves. The atelet hosting the actor calls
	// it on the actor's behalf, authenticating with its own client certificate
	// rather than a bearer token.
	//
	// Authorization is decided on that client certificate and the worker
	// identity attested by atelet. Ateapi verifies that the worker is assigned to
	// the actor and that the actor points back to that exact worker before signing.
	//
	// The certificate in the response is the actor's identity, not the atelet's.
	MintCert(context.Context, *MintCertRequest) (*MintCertResponse, error)
	mustEmbedUnimplementedActorIdentityServer()
}

// UnimplementedActorIdentityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActorIdentityServer struct{}

func (UnimplementedActorIdentityServer) MintJWT(context.Context, *MintJWTRequest) (*MintJWTResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintJWT not implemented")
}
func (UnimplementedActorIdentityServer) MintCert(context.Context, *MintCertRequest) (*MintCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MintCert not implemented")
}
func (UnimplementedActorIdentityServer) mustEmbedUnimplementedActorIdentityServer() {}
func (UnimplementedActorIdentityServer) testEmbeddedByValue()                       {}

// UnsafeActorIdentityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActorIdentityServer will
// result in compilation errors.
type UnsafeActorIdentityServer interface {
	mustEmbedUnimplementedActorIdentityServer()
}

func RegisterActorIdentityServer(s grpc.ServiceRegistrar, srv ActorIdentityServer) {
	// If the following call panics, it indicates UnimplementedActorIdentityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActorIdentity_ServiceDesc, srv)
}

func _ActorIdentity_MintJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintJWTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActorIdentityServer).MintJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActorIdentity_MintJWT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorIdentityServer).MintJWT(ctx, req.(*MintJWTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActorIdentity_MintCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActorIdentityServer).MintCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActorIdentity_MintCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActorIdentityServer).MintCert(ctx, req.(*MintCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ActorIdentity_ServiceDesc is the grpc.ServiceDesc for ActorIdentity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActorIdentity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ateapi.ActorIdentity",
	HandlerType: (*ActorIdentityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MintJWT",
			Handler:    _ActorIdentity_MintJWT_Handler,
		},
		{
			MethodName: "MintCert",
			Handler:    _ActorIdentity_MintCert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ateapi.proto",
}
